nurolopher_blog_homepage:
    path:     /
    defaults: { _controller: NurolopherBlogBundle:Welcome:index}

nurolopher_category:
    resource: "@NurolopherBlogBundle/Resources/config/routing/category.yml"
    prefix: /categories

nurolopher_group:
    resource: "@NurolopherBlogBundle/Resources/config/routing/group.yml"
    prefix: /groups

nurolopher_post:
    resource: "@NurolopherBlogBundle/Resources/config/routing/post.yml"
    prefix: /posts

nurolopher_user:
    resource: "@NurolopherBlogBundle/Resources/config/routing/user.yml"
    prefix: /users

nurolopher_comment:
    resource: "@NurolopherBlogBundle/Resources/config/routing/comment.yml"
    prefix: /comments/

login:
    path:     /login
    defaults: { _controller: NurolopherBlogBundle:User:login }
login_check:
    path: /login_check

logout:
    path: /logout
