security:
    providers:
        main:
            propel:
                class:  Nurolopher\BlogBundle\Model\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            anonymous:  ~
            form_login:
              login_path: login
              check_path:  login_check
    access_control:
      - { path: ^/login/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/users, roles: ROLE_ADMIN }
      - { path: ^/groups, roles: ROLE_ADMIN }
      - { path: ^/categories, roles: ROLE_ADMIN }
    encoders:
        Nurolopher\BlogBundle\Model\User:
          algorithm:  sha512
          encode_as_base64: true
          iterations: 1